(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 583,
	height: 363,
	fps: 24,
	color: "#081842",
	manifest: []
};



// symbols:



(lib.DM043 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 图层 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ACTRPQgincgJhXIAAgUQgKhtgGh5QgOmZgNjIIAFAAQAjGaA8MkQgBAGgGAAIgNhKQANCLAABzQAAAQgBAGgAjFOTQAZkPAboEQAcoVAVj2IAGAAIADBPQg7RmgtFpgAChJLIAGAAQAOBEARClIgEAJQgOg2gTi8gAhcFjQAAhBAKkcQAKkYAEgmQAGAAACAFQgLB4AAGQIgLEcIgHACgABvkHIAAjlIAGAAQACCSAPEGQAREmADBwIAABXIgHABIgkqhgABEqSQgEgqAAhYQAAhcAMh7IAEAAQAEAPAAAZQAAA5gID4gAAuroQgMhVAAhIQAAhWADhyIAJAAIALFaIAAAKQgBAAAAAAQgBAAgBAAQAAAAAAAAQgBAAAAABg");
	this.shape.setTransform(28.1,125.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#B3E1FF").s().p("AkzQfICi/cQgegFACgiQAAgRAmhZIACgEIADgpIANgBQAFgdAGgYIAGAXQASghANgNQAOAKAAAcIgBAjICpgJMAEEAinQidCqirAAQioAAi4iqgAA8F/QAGB6AKBtIAAAUQAJBXAiHbIAGAAQABgFAAgRQAAhygNiLIANBJQAGAAABgFQg8skgjmaIgFAAQANDIAOGYgAitDdQgbIEgZEQIAGAAQAtlpA7xmIgDhPIgGAAQgVD2gcIUgACmOaIAEgIQgRilgOhEIgGAAQATC7AOA2gAhuBkQgKEbAABCIADCPIAHgBIALkcQAAmRALh3QgCgFgGAAQgEAmgKEYgABTipIAkKhIAHgCIAAhWQgDhwgRkoQgPkEgCiTIgGAAgAAkq2QAABXAEArIAIAAQAIj4AAg5QAAgZgEgQIgEAAQgMB8AABcgAAGsnQAABIAMBUIAHAAQAAAAABAAQAAgBABAAQAAAAABAAQAAABABAAIAAgKIgLlbIgJAAQgDBzAABWgAm1tNQAAgTA5giQAxgeAYgFQAEACAIABQAFACAAALQAAAehyBJQgiAAABgfgAEvu7QghgOAAgTQAAglBaAAQBCAAAMA0QAAAigiAAQg/AAgmgQgADPw6QAAgwBVAAQBHAAAAAxQAAAxhHAAQhVAAAAgyg");
	this.shape_1.setTransform(30.9,116.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FDFDFD").s().p("ABcHWQgRh4gMhsQgZjkAAioQAAggABggQADg7AIg4QAtNrBpIVIgGABQhPnCgXicgAg+ETQAEjHAAhhIAFAAQADDfAVKcQAAB3gFA6IgGABQgWnXAAkugAiMDkIgGk3IgChaIAAgGQALj+ADh7IAEAAIAJCNIgPKDgAi/gPIgHjRIgBgOIALlUQAAh1ANidQAQi+AXghQgRDWgRGIIgIDWIgJENIgDAIIgBglgAgRkQQgDhUAAhVQAAhHADhuIACAAIADAAIADBoIAOHOIgDADQgNg3gGikgAg0pwQAAgkAFgnIADAAIADAAIAIBeQAFBOAAA+QAABzgEB4IgFADIgPmNg");
	this.shape_2.setTransform(36.2,111.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("ACTRPQgincgJhXIAAgUQgKhtgGh5QgOmZgNjIIAFAAQAjGaA8MkQgBAGgGAAIgNhKQANCLAABzQAAAQgBAGgAjFOTQAZkPAboEQAPkfANjMIAHDRQgtMMgkEhgAChJLIAGAAQAOBEARClIgEAJQgOg2gTi8gAhcFjQAAhBAKkcQAKkYAEgmIACAAIABBaQgGCPAAEkIgLEcIgHACgABvkHIAAjlIAGAAIAECHQgCAfAAAhQAACqAaDiQAHCTACBIIAABXIgHABIgkqhgAhYphIABAlIgJCyIAIjXgABHqSIgEhnIgDAAIAAgbQAAhcAMh7IAEAAQAEAPAAAZQAAA5gID4gAAuroIgIhfIgCAAQgCggAAgeQAAhWADhyIAJAAIALFaIAAAKQgBAAAAAAQgBAAgBAAQAAAAAAAAQgBAAAAABg");
	this.shape_3.setTransform(28.1,125.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#B3E1FF").s().p("AlAQfICi/cQgegFADgiQAAgRAlhZIACgEIADgpIAOgBQAEgdAGgYIAHAXQARghANgNQAOAKAAAcIgBAjICpgJMAEEAinQidCqiqAAQipAAi4iqgAAwF/QAGB6AJBtIAAAUQAKBXAiHbIAFAAQACgFAAgRQAAhygOiLIAOBJQAFAAACgFQg9skgjmaIgFAAQAODIAOGYgACFGoQAXCdBPHBIAGgBQhpoUgttrQgIA3gDA8IgEiIIgFAAIAADmIAkKhIAHgCIAAhWQgDhIgHiTQAMBrARB4gAiGuCQgNCdAAB1IgLFUIAAAOQgNDNgPEeQgbIEgZEQIAGAAQAlkiAtsLIABAmIADgIIAJkOIAKiyIgCglQAQmIASjWQgXAhgQC+gAgVDlQAAEuAVHYIAFgCQAFg6AAh3QgTqcgDjeIgFAAQAABhgEDGgACZOaIAFgIQgSilgOhEIgFAAQATC7ANA2gAh6BkQgLEbAABCIAECPIAHgBIAKkcQAAknAGiNIAHE3IAEAAIAPqDIgJiNIgEAAQgDB7gLD+IAAAHIgBAAQgEAmgKEYgAATnmQAABUADBUQAGCkAPA3IADgDIgQnOIAFAAQAJj4AAg5QAAgZgFgQIgEAAQgLB8AABcIAAAbIgCAAQgDBtAABIgAgLqeIANGNIAFgDQAEh3AAh0QAAg+gFhOIAGAAQAAAAABAAQAAgBABAAQAAAAABAAQABABAAAAIABgKIgMlbIgGAAQgEBzAABWQAAAeACAgIgDAAQgFAoAAAjgADVoAQgvjNAAgnQAAgaAGgSIAKAAQAdCqBWFxIgKALQgZgwgxjWgAlnrlQAAgRAsgmQAogiANgFQAFACAHAAQAEABAAANQAAASgfAsQggAtgPAAQgjAAAAgdgAC2v2QghgOAAgTQAAglBaAAQBCAAAMA1QAAAigiAAQg/AAgmgRgAkSx0QgFACAAgVQAAgPAKgGQAOgIArAAQAIAAAbAKIAFAMQg1AegQAAg");
	this.shape_4.setTransform(32.1,116.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.shape_2}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-12.9,-6.4,87.7,245.2);


(lib.元件2 = function() {
	this.initialize();

	// 图层 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AjrBoQgSAehmAMQgGgOgEgHQBDgHAjgQQATgJgBgpIAVAAQAAATgDAPQBCATA2AUIgLAVQg6gWg7gUgApWB9QAIgFAAgMIAAjYIBKAAQgHgOgIgPIAVgIQAJASAJATIBJAAIAACHIgXAAIAAgIIhEAAQAMAcAUAVQAfgQAggXIAPASQgbARgjATQAdAXArAIQgIAIgJAPQhagZgkhdIgjAAIAABdQAigNAcgNQAAAQAAAJQggAMggAOIgPAJgAo4AAIB+AAIAAgjIh+AAgAo4g1IB+AAIAAgkIh+AAgAqiCHQATgxAQhAIAYAKIghBwgAHUCLIgEgaQAXACAPAAQAWAAABgWIAAjrIAXAAIAAAvQANAjAQAdQAggbAhglIAUARQgjAkgmAfQAmA8A4AmIgTAWQhOg9gmhXIAACHQAAArgpAAIgnAAgAExCHQghAAABglIAAg7IhAAAIAAhhIAVAAIAABNIArAAIAAhnIhNAAIAAgVIBNAAIAAglIAVAAIAAAlIBRAAIAAAVIhRAAIAABnIArAAIAAhOIAVAAIAABuIgVAAIAAgMIgrAAIAAA4QAAATAQAAIAdAAQARAAABgQIAFgrIAVAJIgFAqQgEAdgjAAgAGIBgQBChGAThKIhNAAIAAgWIBkAAIAAAVQgZBehBBFQgKgLgIgHgAhHBpIAAgZIBChCQAZgZAKgQQAIgQABgRQAAgTgLgLQgLgKgTAAQgeAAgbAaIAAgdQAagVAiAAQAfAAASARQARAQAAAcQAAAVgLAVQgMAUgfAdIgyAzIAAAAIBmAAIAAAagAlIBjIAAg/QgTAIgWAHQgEgJgJgMQBDgOAWgdIhBAAIAJg9IBGAAIABgZIhUAAIAAgRIBUAAIABgZIAVAAIAAAZIAyAAIAAgZIAWAAIAAAZIBGAAIAABDIgVAAIAAgIIgxAAIAAAbIBTAAQgBAVgCANQgEAUgWAAIgJAAIAABIIgWAAIAAg8IiTAAIAAA/gAkpARICJAAIgEgNQARACAKAAQAMAAABgHIACgMIg+AAIAAAaIgWAAIAAgaIg/AAQgHAQgVAOgAkHgeIA5AAIAAgbIg1AAQgBAQgDALgAlPgeIAxAAQAEgKABgRIgyAAgAi4hKIAxAAIAAgZIgxAAgAkChKIA0AAIAAgZIgzAAIgBAZgABsBdIAAjLIBNAAIAADGIgVAAIAAgPIgiAAIAAAUgACCA0IAiAAIAAiOIgiAAgAqrgtIAPgRQAWAQAeAYIgRATQghgegRgMgAqfh6IAOgQQAXASAcAZIgRASQgggfgQgOg");
	this.shape.setTransform(10.2,6);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-60.6,-17.2,141.8,43.6);


(lib.元件1 = function() {
	this.initialize();

	// 图层 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ApPCQIAAiZIhMAAIAAgVIDyAAQgDA7gDAhQgDArgvAAQgcAAgSgCQgCgOgDgLQAaAEAWAAQAcAAACgcQADgWABgpIh1AAIAACZgAHTCLIgEgaQAXACAPAAQAWAAABgWIAAjqIAXAAIAAAvQANAiAQAeQAggbAhgmIAUASQgjAkgmAfQAmA7A4AmIgTAWQhOg8gmhYIAACHQAAAsgpAAIgngBgAjbCHIgFgaQAhAEAcAAQAbAAABgcQAEgqACh0IhjAAQgQAggQAYIgVgLQAlg2ATg9IAYAHIgRApIBzAAQgFCDgDA2QgCAvgvAAQgcAAgfgCgAEwCIQghAAABgmIAAg6IhAAAIAAhiIAVAAIAABNIArAAIAAhmIhNAAIAAgVIBNAAIAAglIAVAAIAAAlIBRAAIAAAVIhRAAIAABmIArAAIAAhNIAVAAIAABuIgVAAIAAgMIgrAAIAAA3QAAATAQAAIAdAAQARAAABgPIAFgrIAVAJIgFAqQgEAdgjAAgAl+BlQBAgJA3gJIgBAWQgvAGhCANgAGHBhQBChGAThKIhNAAIAAgXIBkAAIAAAWQgZBehBBEQgKgLgIgGgAhCBhIAAgeQAXASAdAAQAVAAAOgLQAOgMAAgTQAAgrg8AAIgTAAIAAgWIASAAQA1AAAAgoQAAgmgoAAQgXAAgWARIAAgcQAXgMAdAAQAbAAASAPQASAPAAAYQAAAtguAMIAAABQAYADAPAMQAOAPAAAWQAAAfgWASQgWATgiAAQghAAgTgMgABrBdIAAjLIBNAAIAADHIgVAAIAAgQIgiAAIAAAUgACBA1IAiAAIAAiOIgiAAgAl1AmQAVgXAaglIgyADIgFgUQAfgrAcg9IAWAIQgcA2gbAoIApgBIAYgqIAVALQglA/gkArIBLgLIgEAXIhhAOgAjwgOIATgMQAbAiAWAfIgWAPQgTghgbgjgAnygwIAAghIhPAAIAAAgIgXAAIAAggIhRAAIAAgWIBRAAIAAgmIAXAAIAAAmIBPAAIAAgmIAXAAIAAAmIBRAAIAAAWIhRAAIAAAhg");
	this.shape.setTransform(10.3,5.9);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-60.6,-17.2,141.8,43.6);


(lib.DM0431 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 图层 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#B3E1FF").s().p("AhoExQATgfATAAQAbAAACAaQAAAHgIAJQgJAJgMAAQgKAAgcgUgAhxA+IgQh1IAAgCIgGAAQgoAAACgnQAAgRAmhZIARgoQAFghAHgaIAGAXQASghANgNQAOAKAAAcQgBBsgRA4IAFA1QAQCZAbBRIgDAJQgCAFgLAAQgvAAgZh1gAm1A1QAAgTA5giQAxgcAYgFQAEACAIABQAFACAAALQAAAchyBJQgiAAABgfgAEvg3QghgOAAgTQAAglBaAAQBCAAAMA0QAAAigiAAQg/AAgmgQgADPi2QAAgwBVAAQBHAAAAAxQAAAxhHAAQhVAAAAgyg");
	this.shape.setTransform(30.9,26.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("ACTHlQgijRgJgmIAAgJQgKgwgGg2QgOizgNhYIAFAAQAjC0A8FiQgBACgGAAIgNggQANA9AAAzQAAAHgBACgAjFGTQAZh4AbjjQAcjqAVhsIAGAAIADAjQg7HvgtCfgAChECIAGAAQAOAeARBJIgEAEQgOgYgThTgAhcCcQAAgdAKh8QAKh7AEgRQAGAAACADQgLA0AACwIgLB9IgHAAgABvhzIAAhlIAGAAQACBAAPB0QARCAADAyIAAAmIgHAAIgkkngABEkhQgEgTAAgmQAAgoAMg3IAEAAQAEAHAAALQAAAZgIBtgAAulHQgMglAAggQAAgmADgyIAJAAIALCYIAAAFIgEAAg");
	this.shape_1.setTransform(28.1,51.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#B3E1FF").s().p("AkzHQICit1QgegCACgPQAAgHAmgnIACgCIADgSIANgBQAFgMAGgLIAGAKQASgOANgGQAOAEAAANIgBAPICpgEIEEPOQidBLirAAQioAAi4hLgAA8CoQAGA2AKAwIAAAJQAJAmAiDRIAGAAQABgCAAgHQAAgygNg+IANAgQAGABABgDQg8ligjizIgFAAQANBYAOCygAitBhQgbDjgZB4IAGAAQAtifA7nvIgDgjIgGAAQgVBtgcDpgACmGWIAEgEQgRhIgOgfIgGAAQATBTAOAYgAhuAsQgKB9AAAcIADA/IAHAAIALh9QAAivALg1QgCgCgGAAQgEARgKB6gABThKIAkEoIAHgBIAAgmQgDgxgRiDQgPhxgChBIgGAAgAAkkxQAAAnAEASIAIAAQAIhsAAgaQAAgLgEgHIgEAAQgMA3AAAogAAGljQAAAgAMAlIAHAAIAEAAIAAgEIgLiZIgJAAQgDAzAAAlgAm1lzQAAgJA5gPQAxgNAYgCIAMABQAFABAAAFQAAANhyAgQgiAAABgNgAEvmkQghgGAAgIQAAgRBaAAQBCAAAMAXQAAAPgiAAQg/AAgmgHgADPncQAAgVBVAAQBHAAAAAWQAAAVhHAAQhVAAAAgWg");
	this.shape_2.setTransform(30.9,47.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("ABoFSIAAgMQgKhEgGhNQgOj/gNh+IAFAAQAjEBA8H3QgOgSgGgYQANBXAABIIgHAOQgikrgJg2gAjFI+QAZirAblDQAclNAVibQAJAoAAAKQg7LAgtDkgAChFwIAGAAQAOAqARBoQgSgdgTh1gAhcDfQAAgqAKixQAKivAEgYQgDBOAAD7IgLCxgABvilIAAiQIAGAAQACBdAPCkQARC4ADBFIAAA3QgfkXgMiOgABAntQAAg6AMhOQAIAKAAAQQAAAkgICbQgMgbAAg2gAAio0QAAg2ADhIQAMBHAICSIgLAHQgMg1AAgtg");
	this.shape_3.setTransform(28.1,76.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#B3E1FF").s().p("AkzKWICizuQgegCACgWQAAgLAmg3IAFgdQASgSAGgPIAGAOQARgVAOgIQAOAHAAARIgBAWICpgGIEEVtQidBqirAAQioAAi4hqgAA8DwQAGBNAKBEIAAAMQAJA2AiErIAHgOQAAhIgNhXQAGAYAOASQg8n3gjkBIgFAAQANB+AOD/gAitCLQgbFDgZCrIAGAAQAtjkA7rAQAAgKgJgoQgVCbgcFNgACqI9QgRhogOgqIgGAAQATB1ASAdgAhuA/QgKCxAAAqIAKBYIALixQAAj7ADhOQgEAYgKCvgABThqQAMCMAfEZIAAg3QgDhFgRi6QgPiigChdIgGAAgAAkmyQAAA2AMAbQAIibAAgkQAAgQgIgKQgMBOAAA6gAAGn5QAAAtAMA1IALgHQgIiSgMhHQgDBIAAA2gAm1oRQAAgNA5gUQAxgTAYgEQARAEAAAHQAAAThyAtQgiAAABgTgAEvpWQghgJAAgMQAAgYBaABQBCgBAMAiQAAAVgiAAQg/AAgmgKgADPqlQAAgfBVAAQBHAAAAAfQAAAehHAAQhVAAAAgeg");
	this.shape_4.setTransform(30.9,70.4);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("ABoG3IAAgQQgKhYgGhjQgOlMgNijIAFAAQAjFNA8KOQgOgYgGgfQANBxAABdIgHASQgimDgJhHgAjFLoQAZjdAbmjQAcmxAVjIQAJA0AAAMQg7OUgtElgAChHeIAGAAQAOA3ARCGQgSglgTiYgAhcEhQAAg1AKjnQAKjjAEgfQgDBlAAFGIgLDmgABvjVIAAi7IAGAAQACB3APDVQARDvADBbIAABGQgflqgMi3gABAqBQAAhKAMhlQAIANAAAUQAAAvgIDJQgMgiAAhIgAAircQAAhGADheQAMBdAIC9IgLAJQgMhFAAg6g");
	this.shape_5.setTransform(28.1,100.9);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#B3E1FF").s().p("AkzNaICi5lQgegEACgbQAAgOAmhIIAFglQASgYAGgUIAGATQARgbAOgLQAOAIAAAYIgBAcICpgHIEEcJQidCLirAAQioAAi4iLgAA8E4QAGBjAKBYIAAAQQAJBHAiGDIAHgSQAAhdgNhxQAGAfAOAYQg8qOgjlNIgFAAQANCjAOFMgAitC0QgbGjgZDdIAGAAQAtklA7uUQAAgMgJg0QgVDIgcGxgACqLnQgRiGgOg3IgGAAQATCYASAlgAhuBRQgKDnAAA1IAKBzIALjmQAAlGADhlQgEAfgKDjgABTiJQAMC1AfFsIAAhGQgDhbgRjxQgPjTgCh3IgGAAgAAko1QAABIAMAiQAIjJAAgvQAAgUgIgNQgMBlAABKgAAGqQQAAA6AMBFIALgJQgIi9gMhdQgDBeAABGgAm1qvQAAgQA5gbQAxgZAYgEQARAEAAAJQAAAZhyA7QgiAAABgZgAEvsJQghgLAAgQQAAgeBaAAQBCAAAMArQAAAbgiABQg/AAgmgOgADPtwQAAgnBVAAQBHAAAAAoQAAAnhHABQhVAAAAgpg");
	this.shape_6.setTransform(30.9,93.3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("ACTRPQgincgJhXIAAgUQgKhtgGh5QgOmZgNjIIAFAAQAjGaA8MkQgBAGgGAAIgNhKQANCLAABzQAAAQgBAGgAjFOTQAZkPAboEQAcoVAVj2IAGAAIADBPQg7RmgtFpgAChJLIAGAAQAOBEARClIgEAJQgOg2gTi8gAhcFjQAAhBAKkcQAKkYAEgmQAGAAACAFQgLB4AAGQIgLEcIgHACgABvkHIAAjlIAGAAQACCSAPEGQAREmADBwIAABXIgHABIgkqhgABEqSQgEgqAAhYQAAhcAMh7IAEAAQAEAPAAAZQAAA5gID4gAAuroQgMhVAAhIQAAhWADhyIAJAAIALFaIAAAKQgBAAAAAAQgBAAgBAAQAAAAAAAAQgBAAAAABg");
	this.shape_7.setTransform(28.1,125.5);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#B3E1FF").s().p("AkzQfICi/cQgegFACgiQAAgRAmhZIACgEIADgpIANgBQAFgdAGgYIAGAXQASghANgNQAOAKAAAcIgBAjICpgJMAEEAinQidCqirAAQioAAi4iqgAA8F/QAGB6AKBtIAAAUQAJBXAiHbIAGAAQABgFAAgRQAAhygNiLIANBJQAGAAABgFQg8skgjmaIgFAAQANDIAOGYgAitDdQgbIEgZEQIAGAAQAtlpA7xmIgDhPIgGAAQgVD2gcIUgACmOaIAEgIQgRilgOhEIgGAAQATC7AOA2gAhuBkQgKEbAABCIADCPIAHgBIALkcQAAmRALh3QgCgFgGAAQgEAmgKEYgABTipIAkKhIAHgCIAAhWQgDhwgRkoQgPkEgCiTIgGAAgAAkq2QAABXAEArIAIAAQAIj4AAg5QAAgZgEgQIgEAAQgMB8AABcgAAGsnQAABIAMBUIAHAAQAAAAABAAQAAgBABAAQAAAAABAAQAAABABAAIAAgKIgLlbIgJAAQgDBzAABWgAm1tNQAAgTA5giQAxgeAYgFQAEACAIABQAFACAAALQAAAehyBJQgiAAABgfgAEvu7QghgOAAgTQAAglBaAAQBCAAAMA0QAAAigiAAQg/AAgmgQgADPw6QAAgwBVAAQBHAAAAAxQAAAxhHAAQhVAAAAgyg");
	this.shape_8.setTransform(30.9,116.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape}]}).to({state:[{t:this.shape_2},{t:this.shape_1}]},7).to({state:[{t:this.shape_4},{t:this.shape_3}]},1).to({state:[{t:this.shape_6},{t:this.shape_5}]},1).to({state:[{t:this.shape_8},{t:this.shape_7}]},1).to({state:[]},2).wait(68));

	// 图层 1
	this.instance = new lib.DM043("synched",0);
	this.instance.setTransform(15.8,42.5,1,1,0,0,0,13.9,41.3);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(12).to({_off:false},0).to({_off:true},38).wait(30));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-12.9,-6.4,87.7,65.2);


// stage content:



(lib.dh = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{step1:0,step2:6,"step2":7,"step2":49});

	// timeline functions:
	this.frame_0 = function() {
		/* 在此帧处停止
		时间轴将在插入此代码的帧处停止/暂停。
		也可用于停止/暂停影片剪辑的时间轴。
		*/
	}
	this.frame_6 = function() {
		/* 在此帧处停止
		时间轴将在插入此代码的帧处停止/暂停。
		也可用于停止/暂停影片剪辑的时间轴。
		*/
	}
	this.frame_49 = function() {
		/* 在此帧处停止
		时间轴将在插入此代码的帧处停止/暂停。
		也可用于停止/暂停影片剪辑的时间轴。
		*/
		
		
		this.gotoAndPlay(1);
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(6).call(this.frame_6).wait(43).call(this.frame_49).wait(1));

	// dh
	this.instance = new lib.元件2("synched",0);
	this.instance.setTransform(394.7,317.4);

	this.instance_1 = new lib.元件1("synched",0);
	this.instance_1.setTransform(88.2,317.4);

	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("rgba(0,0,0,0.349)").ss(0.3,1,1).p("ACwDRIMggYIApiJIgHiZItCAaQgJAqgEAoQAAADgBAEQAAAFAAAEQgCAZAAAYQAABHAQBGIANA2QgxAbgbgbIgJg4IgsAEQgBgdAAgfQAAgSABgUQACg3AGg9QAFgtAFgdAkGm6IABgBQAkgaA0AAQAjAAAdANQANAFAMAIQAkAbAAAlQAAAlgkAbQglAag0AAQg0AAgkgaQgNgJgIgLQgQgTAAgZQAAgMAEgKQAAgCABgBQAGgQAOgNQAFgFAGgEgAlCm6IA8AAAnNm5IAAgmQBGgdBFAdIAAAlAkalPIgfABIAABNIAdAAIAAAcIAgAAIAABdQARAJARANQALAIALAKQAMALAKALIDGgDAgFDUQgDgoAAgtQAAgMABgPQADgrAKg7QAKg0AIgXIAOAAIAMAAIAKAAIASAAIAWgBIANg1QAggYAsAYIgNA0AALDTQgCgZAAgaQAAgWAAgWQAAgBAAAAQADhFAKg4QAHgpAJgaAAWDTQgBgYAAgbQAAgZACgaQADg+ALg/QAHglAGgYAj8iIIAAASQhxAWhwgQQgSgCgRgEIAAgWIAAhZIAcAAIAdAAICrAAAgFDUIibABQAAAAAAAAQgQAVgUAUQhPBIhvAAQhwAAhOhIQgighgUglIhMAAQg5AOADA5IADCqQAZAVgZATQhGAeg/gBQg7AAg1gaQgcgaAagMIAQmaQAUhTBRgXIEoAFQAHgIAIgHQAdgbAjgRAAqDTQgCgnAAgwQAAgEAAgEQABhRANhOQADgTADgPAAWDTIgLAAIgQABAAqDTIgUAAABoDPQgIg1gCg2QgEhaAKhYAA8DTIgSAAAo/m4IARAAIBhgBICLgBAo/m4QAHAEAGAEQADACADADQAUAQAHAUQAEALAAAMQAAATgKAQQgJAQgSAMQgkAbg0AAQgUAAgRgEQgdgGgXgRQglgaAAglQAAglAlgbQAlgaA0AAQArAAAgASgAnRlNIhGAAAnRkBIAAg5IAAgTICYgBAnkjlIAAgcIATAAAk5kBIhvAAIgpAAAtqHCQABAAAAAA");
	this.shape.setTransform(440.2,64.9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#414B61").s().p("AgIAiQg7gBg1gaQgcgXAagNQA7AZBFgFIABAAQA2gEA+gUQAZAVgZARQhFAdg8AAIgCAAg");
	this.shape_1.setTransform(352,111);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.lf(["#2F3940","#757EA4","#FFFFFF","#E6E6E6"],[0,0.208,0.722,0.992],50.4,0.6,37.1,-46.8).s().p("Am5CnIAAgDIABADIgBAAgAG4ilIAAgBIACAAIAAABg");
	this.shape_2.setTransform(396.9,93.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#2F3940").s().p("AgKBhIgLgHQADg9ALhAQAHgkAEgZIAKAAIgGAiQgLBOgBBRQABhRALhOIAGgiIASAAIAWgBQgKBbAEBXQgRAJgRAFQACg4AGg9QAFgtAFgdQgFAdgFAtQgGA9gCA4IgSACIgGAAgAgrBSQgBgBgJAAQADgrAMg6QAKg1AIgXIAOAAQgJAagHApQgKA5gDBEIgCABQgCgMgEgDgAgWgdQAHgpAJgaIAKAAQgEAZgHAkQgLBAgDA9IgGgDQgCAFgGAEQADhEAKg5gAAOBfIAAAAgAgGhgg");
	this.shape_3.setTransform(444.8,66.8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#7880A6").s().p("AA6BZQhCAAgIgEQgLgGgOgXQgEhPg1g+IDGgDQgIAXgKA0QgNA7gDArIgIAAg");
	this.shape_4.setTransform(432.6,66);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#323C52").s().p("ACPC1QAOAXALAGQAJAEBEAAIAIAAIgBAbQAAAtADAoIibABIAAAAQAphAAChSgAD8DxIABgbQAJAAABABQAEACACAMIAAABIACAAIAAAsQAAAaACAZIgSABQgDgoAAgtgAEcFFIgBgzIACgzIALAHIAGAAIAAAIQAAAwACAnIgUAAIAAAAgAERFFQgCgZAAgaIAAgsIAAgBQAGgEACgFIAGADIgCAzIABAzgAERFFIAAAAgAEdDfIAAAAgAD9DWIAAAAgAGoCFIAAgJIACAHIgCACIAAAAgAGiCEIACgIIADgIIABAIIAAAJgAGoB8gAmpioQAUAAARgCIAAAGQgUAAgRgEgAgfkiIACABIgDACIABgDgAksk+IgNgIIARAAIACANIgGgFg");
	this.shape_5.setTransform(414,53.5);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#BEC2D4").s().p("AjYFKQhYgrgUgeQgTgfgFgCIAAgNQAAhdBAhEIAPgPQAdgcAigPIAAhYIAdAAIAAgdIATAAIAAg4IANAHQAiAVAFARIgLALIgpAAIApAAIgfAdIgdAAIAdAAIgQAOQgaAaABAWQgBAXAUAeIgkgGIAAgVIAAAVIAkAGQBwAQBvgWIAAgRQARAIARAMQAMALAJAMQAgApACA2QAAA2gfAqQgfAogVATQgVARgfATQgfATg0APQgMADgPAAQgvAAhCgggAHTCHIADAAIgBAIgAh1h9gAmwisQglgaAAgmQAAglAlgaQAlgbA0AAQAqAAAhATIAMAIIAGAEIACAcIAAAHQABA3gSAVQgVAag5AGQgSACgTABQgdgHgXgQgAAZjhQgMgKgGgLQAAgMAEgLIgLADQhOAUg6AAQgtAAgqgNQgGgUgVgQIgBgNIBhAAICKgBIA7gBIgLAJQgOAOgHAQIAAACIADgBIgDgBQAHgQAOgOIALgJIABAAQAkgaA0AAQAjAAAdAMQAOAVAAAKQAAAZgnAeQguAkg4AAQgUAAgYgXgAialbQBFgcBFAcIAAAmIiKABg");
	this.shape_6.setTransform(409.5,51.7);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#5E6D91").s().p("AuxHCQAfggABh2IADiXQAAgiA5gVQAsgQAvAAQALAAAZASQAFACATAeQAUAeBYArQBYArA0gOQA0gOAhgUQAfgSAVgSQAVgTAfgoQAfgpAAg2QgCg1gggpQgJgMgMgKQALAIALAKQAMAKAKAMQA1A9AEBPQgCBTgqBAQgPAVgUAUQhPBIhvAAQhwAAhOhIQgighgUglIhMAAQg5AOADA4IADCrQg+AUg2AFIgBgEgAAqELIgJg4QgIg2gCg1QACA1AIA2IgqADIgBg8IABglIgBAlIABA8IgSAAQgCgmAAgwIAAgIIAUgDQAPgEARgJIAQgMQAcgXARgvIAGABQgCAYABAZQALAPAlgBQAkgBBXABQBWAABNgJQBNgJB5AAQBVAADwgQIgpCIIsgAZIANA2QgYANgUAAQgTAAgNgNgABpDVQgQhHAAhGQAABGAQBHgAAhDTIAAAAgAokhsQgUggABgXQgBgVAagaIAQgPIAfgcIALgMQgFgRgigVIgNgHIAAgTIhHAAQALgQAAgTQgBgMgEgMQAqANAtAAQA6AABPgUIAMgCQgEAKAAAMQAAAYAQAUQgQgUAAgYQAGALAMALQAYAWAUAAQA4AAAugkQAngeAAgZQAAgKgOgUQANAFAMAIQAkAbAAAlQAAAlgkAaQglAbg0AAQg0AAgkgbQgNgIgIgLIgfAAIiYACICYgCIAABOIhvAAIBvAAIAcAAIAAAcIAhAAIAABcIAAATQhCANhBAAQgvAAgvgHgAlkjhIiqAAgArRkYQA5gHAVgaQASgVgBg3IAAgHIgCgcQAVARAGATQAEAMABAMQAAATgLAQQgIAPgTANQgjAbg0AAgAmAlLgApZmEIAAAAg");
	this.shape_7.setTransform(447.3,64.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#E6E6E6").s().p("AvyEUIAQmXQAThWBRgWIEpAFQhABEAABdIAAANQgZgRgLAAQgvAAgsAQQg5AVAAAhIgDCWQgBB2gfAgIAAADIgWABQg7AAgxgVgABejnIANg1QAggYAsAYIgNAzINCgaIAHCcQjwAQhVAAQh5AAhNAJQhNAJhWgBQhXgBgkACQglABgLgPQgBgZACgYIACgCIgBgHIABgIIgDAAIgCAHIgDAIQgRAwgcAXIgQAMQgEhaAKhagACdiVQAEgqAJgqQgJAqgEAqg");
	this.shape_8.setTransform(440.8,80.3);

	this.instance_2 = new lib.DM0431("synched",0);
	this.instance_2.setTransform(354.3,195.3,0.8,0.8,0,0,0,34.1,110.9);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f().s("rgba(0,0,0,0.349)").ss(0.3,1,1).p("ACwDRIMggYIApiJIgHiZItCAaQgJAqgEAoQAAADgBAEQAAAFAAAEQgCAZAAAYQAABHAQBGgAkGm6IABgBQAkgaA0AAQAjAAAdANQANAFAMAIQAkAbAAAlQAAAlgkAbQglAag0AAQg0AAgkgaQgNgJgIgLQgQgTAAgZQAAgMAEgKQAAgCABgBQAGgQAOgNQAFgFAGgEgAlCm6IA8AAAnNm5IAAgmQBGgdBFAdIAAAlAo/m4IARAAIBhgBICLgBAoXlNQAKgQAAgTQAAgMgEgLQgHgUgUgQQgDgDgDgCQgGgEgHgEAnRkBIAAg5IAAgTICYgBIAABNIAdAAIAAAcIAgAAIAABdAoXlNIBGAAAnkjlIAAgcIATAAIApAAIBvAAAoAiMIAAhZIAcAAIAdAAICrAAAkalPIgfABAoAiMIAAAWQARAEASACQBwAQBxgWIAAgSAAYhNIjGADQgKgLgMgLQgLgKgLgIQgRgNgRgJAgFDUIibABQAAAAAAAAQgQAVgUAUQhPBIhvAAQhwAAhOhIQgighgUglIhMAAQg5AOADA5IADCqQAZAVgZATQhGAeg/gBQg7AAg1gaQgcgaAagMIAQmaQAUhTBRgXIEoAFQAHgIAIgHQAdgbAjgRABkhOIANg1QAggYAsAYIgNA0ABOhNIAWgBAA8hNIASAAAAqDTQgCgnAAgwQAAgEAAgEQABhRANhOQADgTADgPIgKAAQgGAYgHAlQgLA/gDA+QgCAaAAAZQAAAbABAYAA8DTQgBgdAAgfQAAgSABgUQACg3AGg9QAFgtAFgdAALDTQgCgZAAgaQAAgWAAgWQAAgBAAAAQADhFAKg4QAHgpAJgaIAMAAAgFDUQgDgoAAgtQAAgMABgPQADgrAKg7QAKg0AIgXIAOAAAALDTIALAAAAqDTIgUAAAgFDUIAQgBABoDPQgIg1gCg2QgEhaAKhYABoDPIgsAEABoDPIAJA4QAbAbAxgbIgNg2AAqDTIASAAAoXlNQgJAQgSAMQgkAbg0AAQgUAAgRgEQgdgGgXgRQglgaAAglQAAglAlgbQAlgaA0AAQArAAAgASAtqHCQABAAAAAA");
	this.shape_9.setTransform(136.9,64.9);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#414B61").s().p("AgIAiQg7gBg1gaQgcgXAagNQA7AZBFgFIABAAQA2gEA+gUQAZAVgZARQhFAdg8AAIgCAAg");
	this.shape_10.setTransform(48.7,111);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.lf(["#2F3940","#757EA4","#FFFFFF","#E6E6E6"],[0,0.208,0.722,0.992],50.4,0.6,37.1,-46.8).s().p("Am5CnIAAgDIABADIgBAAgAG3ilIAAgBIADAAIAAABg");
	this.shape_11.setTransform(93.7,93.2);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#7880A6").s().p("AA7BZQhCAAgKgEQgLgGgOgXQgDhPg2g+IDGgDQgHAXgLA0QgMA7gCArIgIAAg");
	this.shape_12.setTransform(129.4,66);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#2F3940").s().p("AgKBhIgLgHQADg9ALhAQAHgkAEgZQgEAZgHAkQgLBAgDA9IgGgDQgCAFgGAEQADhEAKg5QAHgpAJgaIAKAAIAKAAIgGAiQgLBOgBBRIgGAAgAAIg+IAGgiIASAAQgFAdgFAtQgGA9gCA4IgSACQABhRALhOgAgrBSQgBgBgJAAQADgrAMg6QAKg1AIgXIAOAAQgJAagHApQgKA5gDBEIgCABQgCgMgEgDgAAWgWQAFgtAFgdIAWgBQgKBbAEBXQgRAJgRAFQACg4AGg9gAAOhgg");
	this.shape_13.setTransform(141.5,66.8);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#323C52").s().p("ACPC1QAOAXALAGQAJAEBEAAIAIAAQAJAAABABQAEACACAMIAAABIACAAIAAgBQAGgEACgFIAGADIALAHIAGAAIAAAIQAAAwACAnIgUAAIgBgzIACgzIgCAzIABAzIgLAAQgCgZAAgaIAAgsIAAAsQAAAaACAZIgSABQgDgoAAgtIABgbIgBAbQAAAtADAoIibABIAAAAQAphAAChSgAGiCEIACgIIADgIIABAIIAAAJIAAgJIACAHIgCACgAmpioQAUAAARgCIAAAGQgUAAgRgEgAgfkiIACABIgDACIABgDgAksk+IgNgIIARAAIACANIgGgFg");
	this.shape_14.setTransform(110.7,53.5);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#BEC2D4").s().p("AjYFKQhYgrgUgeQgUgfgDgCIgBgNQAAhdBAhEIAPgPQAdgcAjgPIAAAVIAiAGQBxAQBugWIAAgRQASAIARAMQAMALAKAMQAfApABA2QACA2ggAqQgfAogWATQgTARghATQgdATg1APQgMADgPAAQgvAAhCgggAHUCHIACAAIgBAIgAirATIAAAAgAjNANIAAgVIAAhYIAcAAIAdAAIgdAAIAAgdIATAAIApAAIgpAAIAAg4IAMAHQAjAVAGARIgMALIgfAdIgQAOQgaAaAAAWQAAAXATAeIgigGgAmxisQgkgaAAgmQAAglAkgaQAlgbA0AAQArAAAhATIAMAIIAHAEIgCgNIBhAAICLgBIA6gBIgLAJQgPAOgFAQIgBACIADgBIgCgBQAFgQAPgOIALgJIAAAAQAlgaA0AAQAjAAAcAMQAPAVAAAKQABAZgoAeQguAkg5AAQgTAAgYgXQgMgKgGgLQAAgMAEgLIgLADQhOAUg7AAQgrAAgqgNQgIgUgTgQIACAcIAAAHQgBA3gQAVQgWAag6AGQgRACgTABQgdgHgYgQgAialbQBGgcBFAcIAAAmIiLABgAgPk1g");
	this.shape_15.setTransform(106.3,51.7);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#5E6D91").s().p("AuxHCQAeggACh2IACiXQABgiA5gVQArgQAxAAQAKAAAaASQADACAUAeQAUAeBYArQBYArA0gOQA1gOAfgUQAhgSATgSQAWgTAfgoQAggpgCg2QgBg1gfgpQgKgMgMgKQALAIALAKQALAKAKAMQA2A9ADBPQgBBTgpBAQgQAVgUAUQhPBIhvAAQhwAAhOhIQgjghgTglIhMAAQg6AOAEA4IADCrQg+AUg2AFIgBgEgAAqELIgKg4QgHg2gCg1QACA1AHA2IgpADIgBg8IABglIgBAlIABA8IgSAAQgCgmAAgwIAAgIIAUgDQAPgEARgJIARgMQAcgXARgvIAGABQgCAYAAAZQALAPAlgBQAlgBBWABQBWAABNgJQBNgJB5AAQBUAADxgQIgqCIIsfAZQgQhHAAhGQAABGAQBHIANA2QgYANgTAAQgTAAgOgNgAolhsQgTggAAgXQAAgVAagaIAQgPIAfgcIAMgMQgGgRgjgVIgMgHIAAgTIhGAAQAKgQgBgTQAAgMgDgMQAqANArAAQA7AABQgUIALgCQgEAKAAAMQAAAYAPAUQgPgUAAgYQAGALAMALQAYAWATAAQA5AAAugkQAogegBgZQAAgKgPgUQAOAFALAIQAlAbAAAlQAAAlglAaQgkAbg0AAQg0AAglgbQgMgIgJgLIgeAAIiYACICYgCIAABOIhvAAIBvAAIAdAAIAAAcIAfAAIAABcIAAATQhBANhBAAQgvAAgwgHgAljjhIirAAgArSkYQA6gHAWgaQAQgVABg3IAAgHIgCgcQATARAIATQADAMAAAMQABATgKAQQgKAPgSANQgkAbg0AAgAmAlLg");
	this.shape_16.setTransform(144.1,64.6);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#E6E6E6").s().p("AvyEUIAQmXQAUhWBRgWIEoAFQhABEAABdIABANQgagRgKAAQgxAAgrAQQg5AVgBAhIgCCWQgCB2geAgIAAADIgWABQg7AAgxgVgABejnIANg1QAggYAsAYIgNAzINCgaIAHCcQjxAQhUAAQh5AAhNAJQhNAJhWgBQhWgBglACQglABgLgPQAAgZACgYIACgCIgCgHIABgIQAEgqAJgqQgJAqgEAqIgCAAIgDAHIgCAIQgRAwgcAXIgRAMQgEhaAKhag");
	this.shape_17.setTransform(137.6,80.3);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f().s("#BA3911").ss(2,2,1).rr(-290,-180,580,360,10);
	this.shape_18.setTransform(291.5,181.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.instance_2},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape},{t:this.instance_1},{t:this.instance}]}).wait(50));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(292,182,582,362);

})(dh = dh||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var dh, images, createjs, ss;